Практика 8 выполнена
fluffystar43/Mathematical-methods-of-data-analysis pull request #10
Opened 2021-04-15 08:29 UTC by REPIRAS

2021-04-15 08:32 UTC, fluffystar43 requested changes

2021-04-15 08:32 UTC, fluffystar43 commented on 08_pract_regexp/regexp.py
> +    for i in mass:
Название массива нужно уточнить

2021-04-15 08:32 UTC, fluffystar43 commented on 08_pract_regexp/regexp.py
> +        '0.100.200.300', 'a.b.c.d', '192.168.0.', '1234.2345.3456.4567']
Название массива нужно уточнить

2021-04-15 08:32 UTC, fluffystar43 commented on 08_pract_regexp/regexp.py
> +        '2016 03 12', '5.3.2016']
Название массива нужно уточнить

2021-04-15 08:32 UTC, fluffystar43 commented on 08_pract_regexp/regexp.py
> +        'test.exe', '~!@$%.png', '<?php test.png ?>']
Название массива нужно уточнить

2021-04-15 08:32 UTC, fluffystar43 commented on 08_pract_regexp/regexp.py
> +            print(i, 'Не подходит')
Можно записать в 2 строки

2021-04-15 08:36 UTC, fluffystar43 approved these changes

2021-04-17 05:32 UTC, stanislavlyalin requested changes

2021-04-17 05:32 UTC, stanislavlyalin commented on 08_pract_regexp/regexp.py
> +        else: print(i, 'Не подходит')
Можно сделать чуть более "питоново":
```python
print(i, 'Подходит' if result else 'Не подходит')
```

2021-04-17 05:32 UTC, stanislavlyalin commented on 08_pract_regexp/regexp.py
> +    for i in massData:
`i` - название не информативное. Может `testSample`?

2021-04-17 05:32 UTC, stanislavlyalin commented on 08_pract_regexp/regexp.py
> +regPattern = r'(0[1-9]|[12][0-9]|3[01])[.](0[1-9]|1[012])[.]((19|20)\d\d)'
Решили перевыполнить задачу :)
На самом деле точку можно проверить как `\.`, что несколько упростит выражение. И нет необходимости ограничивать год.

2021-04-17 05:32 UTC, stanislavlyalin commented on 08_pract_regexp/regexp.py
> +regPattern = r'^[a-z]+\.(png|jpg|jpeg|gif)$'
Буквы в имени могут быть и заглавными

2021-04-21 15:52 UTC, merged