Практика 9 - Разработка приложений с графическим интерфейсом с помощью PyQt5
fluffystar43/Mathematical-methods-of-data-analysis pull request #11
Opened 2021-05-22 09:14 UTC by fluffystar43

2021-05-22 14:52 UTC, Kolompay requested changes
Добавлены замечания

2021-05-22 14:52 UTC, Kolompay commented on 09_pract_pyqt/calculator.py
> +                self.textEditResult.setText(str(x**y))
Можно сократить количество строк, записав тело условия после двоеточия

2021-05-22 14:53 UTC, Kolompay approved these changes

2021-05-24 08:05 UTC, stanislavlyalin requested changes

2021-05-24 08:05 UTC, stanislavlyalin commented on 09_pract_pyqt/calculator.py
> +        self.pbExponentation.clicked.connect(lambda: self.calculate(Operation.power.value))
Лучше передавать `Operation.plus` вместо `Operation.plus.value` и дальше по аналогии

2021-05-24 08:05 UTC, stanislavlyalin commented on 09_pract_pyqt/calculator.py
> +    def calculate(self, Enum):
`Enum` - это тип. Для параметра лучше выбрать другое название, например, `operation`

2021-05-24 08:05 UTC, stanislavlyalin commented on 09_pract_pyqt/calculator.py
> +            elif (Enum == 5): self.textEditResult.setText(str(x**y))
Проверки лучше делать так:
```python
if operation == Operation.plus:
    # действие
```

2021-05-24 08:05 UTC, stanislavlyalin commented on 09_pract_pyqt/calculator.py
> +            elif (Enum == 5): self.textEditResult.setText(str(x**y))
В каждой строке выполняется одинаковый код: приведение к строке, установка текста в textEditResult. Лучше в отдельную переменную сохранить результат, а после записать его в textEditresult

2021-05-29 12:17 UTC, merged