Практика 3 - Кластеры
fluffystar43/Mathematical-methods-of-data-analysis pull request #2
Opened 2021-02-13 08:33 UTC by fluffystar43

Выполнено задание по практике №3.

2021-02-16 08:46 UTC, REPIRAS requested changes

2021-02-16 08:46 UTC, REPIRAS commented on 03_pract_kmeans/k_means.py
> +        i += 1
Можно было использовать стандартную библиотеку random, тем самым, сократить объем кода.☻

2021-02-16 09:15 UTC, REPIRAS reviewed
Замечание было исправлено.

2021-02-16 09:33 UTC, REPIRAS approved these changes

2021-02-22 08:34 UTC, stanislavlyalin requested changes

2021-02-22 08:34 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +def dist(A, B, R):
Функция вычисляет евклидово расстояние, поэтому предлагаю переименовать в `euclidean_distance`

2021-02-22 08:34 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +def dist(A, B, R):
Если `A` и `B` массивы, длину можно не передавать, а вычислить её как `len(A)`

2021-02-22 08:34 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +    return r
Код в строках 5-9 написан не "питоново". В питоне есть [генераторы списков](https://younglinux.info/python/feature/generators), с помощью которых можно сформировать массив квадратов разностей так:
```python
squared_diff = [(A[i]-B[i])**2 for i in range(len(A))]

# или даже так
squared_diff = [(a_i-b_i)**2 for a_i, b_i in zip(A, B)]
```
Затем достаточно только сложить элементы массива и извлечь корень:
```python
r = np.sqrt(sum(squared_diff))
```
Более того, если `A` и `B` - это numpy array, то вычислить расстояние можно в одну строку кода:
```python
return np.sqrt(np.sum(np.power(A-B, 2)))
```

2021-02-22 08:34 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +    m = int(X.size/X.ndim)
Для извлечения `m` и `n` можно брать свойство `shape` у `X`. `shape` - это кортеж, определяющий размерности многомерной матрицы. В данном случае `m = X.shape[0]`, а `n = X.shape[1]`.

2021-02-22 08:34 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +            centers[i][j] = random.uniform(Min[j], Max[j])
В numpy должна быть аналогичная функция, которая генерирует сразу матрицу случайных чисел заданного размера. С её использованием строки 29-32 можно объединить в одну.

2021-02-22 08:34 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +    while True:
Условие выхода из цикла лучше прописать здесь, чтобы код был более наглядным.

2021-02-22 08:34 UTC, stanislavlyalin commented on 03_pract_kmeans/k_means.py
> +            print("Центры:")
Лучше, чтобы функция не выводила на экран ничего. Это не её задача. Она должна только вычислять центры кластеров. Вывод значений можно сделать после вызова функции.

2021-02-27 11:44 UTC, fluffystar43 reviewed
Всё исправил.

2021-03-02 17:11 UTC, merged