Практика 4 – k ближайших соседей
fluffystar43/Mathematical-methods-of-data-analysis pull request #3
Opened 2021-02-13 08:35 UTC by REPIRAS

Выполнено задание по практике №4.

2021-02-16 08:42 UTC, fluffystar43 requested changes

2021-02-16 08:42 UTC, fluffystar43 commented on 04_pract_kNN/kNN.py
> +    b = b[0:k]
Для более понятного анализа кода необходимо указывать названия, отражающие суть происходящего.

2021-02-16 09:16 UTC, fluffystar43 reviewed
Замечание было исправлено!

2021-02-16 09:35 UTC, fluffystar43 approved these changes

2021-02-22 08:46 UTC, stanislavlyalin requested changes

2021-02-22 08:46 UTC, stanislavlyalin commented on 04_pract_kNN/kNN.py
> +def dist(p1, p2):
Лучше переименовать в `euclidean_distance`, чтобы название отражало суть функции.

2021-02-22 08:46 UTC, stanislavlyalin commented on 04_pract_kNN/kNN.py
> +    obj = new[16]
Строки 7-13: очень громоздкое решение. К тому же привязка к числу особей в выборке. Функция должна быть универсальной и работать не только для обезьянок, а для любых многомерных данных. Предлагаю исправить так:
1. выполнить стандартизацию sub_X, т.е. для каждого массива-столбца выполнить следующее: из каждого элемента вычесть среднее массива-столбца, а затем поделить на среднеквадратическое отклонение массива-столбца. Можете для этого написать свою небольшую функцию, а можете использовать [StandardScaler из sklearn](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html). При этом параметры стандартизации нужно запомнить, т.е. для каждого столбца запомнить среднее и среднеквадратическое отклонение.
2. выполнить стандартизацию объекта `obj`. Из него вычесть поэлементно массив средних значений по столбцам, а затем поделить поэлементно на массив среднеквадратических отклонений.
Текста много, но в коде это выглядит просто. Используйте функции `np.mean` и `np.std` с правильными параметрами `axis`.

2021-02-28 12:19 UTC, REPIRAS reviewed
Исправил все замечания

2021-03-02 17:13 UTC, merged