Практика 2 - Введение в Python
fluffystar43/Mathematical-methods-of-data-analysis pull request #5
Opened 2021-04-11 17:36 UTC by REPIRAS

2021-04-11 17:42 UTC, fluffystar43 requested changes
Необходимо исправить замечания

2021-04-11 17:42 UTC, fluffystar43 commented on 02_pract_python/intro_var13.py
> +def funcWords(list):
Лучше переименовать в characterSort

2021-04-11 17:42 UTC, fluffystar43 commented on 02_pract_python/intro_var13.py
> +
Необходимо убрать одну из строчек

2021-04-11 17:42 UTC, fluffystar43 commented on 02_pract_python/intro_var13.py
> +
Необходимо убрать одну из строчек

2021-04-11 17:48 UTC, fluffystar43 approved these changes
Замечания были исправлены!

2021-04-11 19:30 UTC, stanislavlyalin requested changes

2021-04-11 19:30 UTC, stanislavlyalin commented on 02_pract_python/intro_var13.py
> +def massAbs(x, y):
Название функции не очень информативное. В названии должно быть упоминание про вычисление разности массивов.

2021-04-11 19:30 UTC, stanislavlyalin commented on 02_pract_python/intro_var13.py
> +        z = [abs(x[i] - y[i]) for i in range(len(x))]
Добавьте проверку, что `x` и `y` являются массивами (`type(x) is list` & `type(y) is list`). Проверьте, что размеры массивов совпадают, иначе выбрасывайте исключение

2021-04-11 19:30 UTC, stanislavlyalin commented on 02_pract_python/intro_var13.py
> +        return z
Формирование `z` и возврат `z` можно объединить, сократив размер функции до 1 строки

2021-04-11 19:30 UTC, stanislavlyalin commented on 02_pract_python/intro_var13.py
> +    return result
Строки тоже 15 и 16 можно объединить в одну

2021-04-11 19:30 UTC, stanislavlyalin commented on 02_pract_python/intro_var13.py
> +    return math.sqrt(sum([(A[i] - B[i])**2 for i in range(len(A))]))
Попробуйте параллельно итерироваться по элементам массива `A` и `B`, используя функцию [`zip`](https://realpython.com/python-zip-function/). Это немного упростит код функции `euclidean_distance`

2021-04-12 17:46 UTC, stanislavlyalin requested changes

2021-04-12 17:46 UTC, stanislavlyalin commented on 02_pract_python/intro_var13.py
> +    if((type(x) is list) & (type(y) is list) & (len(x) == len(y))):
Оператор `&` - это побитовое "И". Здесь нужно использовать `and`. И большинство скобок в данном случае избыточно.

2021-04-13 03:16 UTC, merged