Выполнено задание.
fluffystar43/Mathematical-methods-of-data-analysis pull request #6
Opened 2021-04-14 13:24 UTC by fluffystar43

2021-04-14 13:36 UTC, REPIRAS requested changes
Добавил замечания

2021-04-14 13:36 UTC, REPIRAS commented on 05_pract_decision_tree/classify.py
> +
Убрать строки кода с заданием

2021-04-14 13:36 UTC, REPIRAS commented on 05_pract_decision_tree/decision_tree.py
> +
Убрать строки кода с заданием

2021-04-14 13:36 UTC, REPIRAS commented on 05_pract_decision_tree/decision_tree.py
> +
Убрать строки кода с заданием

2021-04-14 13:36 UTC, REPIRAS commented on 05_pract_decision_tree/classify.py
> +    answer = 0
Убрать поле answer

2021-04-14 13:36 UTC, REPIRAS commented on 05_pract_decision_tree/classify.py
> +    return answer
return можно написать в условии, пропадет лишняя строчка кода

2021-04-14 13:36 UTC, REPIRAS commented on 05_pract_decision_tree/decision_tree.py
> +
Убрать строки кода с заданием

2021-04-14 13:36 UTC, REPIRAS commented on 05_pract_decision_tree/decision_tree.py
> +    return info
Можно написать "return -info", пропадет лишняя строчка кода

2021-04-14 13:43 UTC, REPIRAS approved these changes

2021-04-17 03:41 UTC, stanislavlyalin requested changes

2021-04-17 03:41 UTC, stanislavlyalin commented on 05_pract_decision_tree/decision_tree.py
> +            k = np.unique(X[:,i])
`k` - не слишком понятное имя. Может лучше `X_i_unique_values`? Переменная `m` не нужна. Можно тогда будет просто взять `len(X_i_unique_values)`

2021-04-17 03:41 UTC, stanislavlyalin commented on 05_pract_decision_tree/decision_tree.py
> +            for j in range(m):
Можно итерироваться  прямо по значениям `X_i_unique_values`:
```python
for value in X_i_unique_values:
    ...
```

2021-04-17 03:41 UTC, stanislavlyalin commented on 05_pract_decision_tree/decision_tree.py
> +                T_i = list(Y).count(Y[j])
Пытаюсь понять код. Похоже, он работает не верно. `j` - это индекс уникального значения `i`-го столбца. Например, у нас 2 уникальных значения. А строк в таблице 10. Тогда `count(Y[0])` вернёт количество элементов `Y`, соответствующих первому значению в `Y`, а `count(Y[1])` - количество элементов `Y`, соответствующих второму значению в `Y`, что неверно. Правильнее для каждого уникального значения находить индексы в столбце `X[i]`, а потом по этим индексам брать значения из `Y`. Вот, кстати, строкой ниже массивы для вычисления `Info` формируются правильно. В качестве `T_i` можно брать длину этих массивов.

2021-04-17 03:41 UTC, stanislavlyalin commented on 05_pract_decision_tree/decision_tree.py
> +        p_i = list(set).count(set[i])/m
Здесь та же ошибка, что я описал ранее. `i` - это счётчик по уникальным значениям, но вы по этому индексу берёте значения из `set`, который является массивом с не-уникальными значениями

2021-04-21 15:36 UTC, merged