Практика 6 - Сжатие изображений с помощью полиномиальной регрессии
fluffystar43/Mathematical-methods-of-data-analysis pull request #7
Opened 2021-04-14 13:40 UTC by REPIRAS

2021-04-14 13:45 UTC, fluffystar43 requested changes

2021-04-14 13:45 UTC, fluffystar43 commented on 06_pract_regression/regression.py
> +# Вариант 3
Добавить описание задания.

2021-04-14 13:48 UTC, fluffystar43 approved these changes

2021-04-17 05:38 UTC, stanislavlyalin requested changes

2021-04-17 05:38 UTC, stanislavlyalin commented on 06_pract_regression/regression.py
> +plt.show()
А для пятой степени? :) Код сильно дублируется, поэтому сделайте 2 функции
* первая принимает массив и степень полинома и возвращает массив предсказаний
* вторая принимает массив и список степеней полиномов. Для каждой степени вызывает первую функцию и отображает на одном (!) графике все предсказания. Добавьте легенду к графику

2021-04-21 15:48 UTC, stanislavlyalin requested changes

2021-04-21 15:48 UTC, stanislavlyalin commented on 06_pract_regression/regression.py
> +     X = np.array(list).transpose()
Можно сделать несколько проще:
```python
X = np.array([x**power for power in range(degree + 1)]).T
```

2021-04-21 15:48 UTC, stanislavlyalin commented on 06_pract_regression/regression.py
> +     lm.fit(X, y)
Вектор `y` необходимо передать в функцию как параметр

2021-04-21 15:48 UTC, stanislavlyalin commented on 06_pract_regression/regression.py
> +    plt.plot(y, 'b-')
Вектор `y` необходимо передать в функцию

2021-04-21 15:48 UTC, stanislavlyalin commented on 06_pract_regression/regression.py
> +    plt.grid()
Добавьте легенду, подписи к осям и название графика

2021-04-21 17:56 UTC, merged