Практика 7 - Парсинг web-страниц на Python
fluffystar43/Mathematical-methods-of-data-analysis pull request #8
Opened 2021-04-14 13:50 UTC by fluffystar43

Выполнено задание.

2021-04-14 13:56 UTC, REPIRAS requested changes

2021-04-14 13:56 UTC, REPIRAS commented on 07_pract_parsing/parser.py
> +print('Комментариев в статье: ', len(comments))
Убрать лишний пробел после двоеточия

2021-04-14 13:58 UTC, REPIRAS approved these changes

2021-04-17 03:44 UTC, stanislavlyalin requested changes

2021-04-17 03:44 UTC, stanislavlyalin commented on 07_pract_parsing/parser.py
> +doc = bs(codecs.open('article.html', encoding='utf-8', mode='r').read(), 'html.parser')
Добавьте возможность указать URL через вызов функции `input()` и загружайте страницу по этому URL с помощью библиотеки `requests`

2021-04-21 15:51 UTC, stanislavlyalin requested changes

2021-04-21 15:51 UTC, stanislavlyalin commented on 07_pract_parsing/parser.py
> +file.close()
Нет необходимости сохранять контент в файл. Можно сразу передать его в `BeautifulSoup`

2021-04-21 18:14 UTC, merged